# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-sync
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: flux-sync
#   interval: 1h
#   retryInterval: 1m
#   timeout: 5m
#   path: ./cluster
#   prune: true


---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-sync
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes/clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
