apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ingress-nginx-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - port: metrics
    path: /metrics
  jobLabel: ingress-nginx
  selector:
    matchLabels:
    # matchLabels: [] # all labels in the given in the service above should match.
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
  namespaceSelector:
    matchNames:
      - ingress-nginx