
name: Artillery Load Test
on:
  schedule:
    - cron: "0 */6 * * *" # Run every 6 hours
jobs:
  artillery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Execute load tests
        uses: artilleryio/action-cli@v1
        with:
          command: run ./.github/tool/asciiart-load-test.yml --record --key ${{ secrets.ARTILLERY_API_KEY }}